// Next & React Imports
import Head from 'next/head';

// MUI Imports
import { CssBaseline } from '@mui/material';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

// Project & Style Imports
import NavBar from '@/components/NavBar';
import SampleNavBar from '@/components/SampleNavBar';
import styles from '@/styles/Home.module.css';


export default function Home() {
  return (
    <>
      <Head>
        <title>Tyler Hum Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="background">
        <CssBaseline />
        <Box className="centered-container">
          <NavBar />
          <Box>
            <Typography variant='h1'>
              Hero Banner
            </Typography>
          </Box>
          <Box>
            <Typography variant='h3'>
              Body 1
            </Typography>
          </Box>
          <Box>
            <Typography variant='h3'>
              Body 2
            </Typography>
          </Box>
          <Box>
            <Typography variant='h3'>
              Body 3
            </Typography>
          </Box>
          <Box>
            <Typography variant='h2'>
              About Me
            </Typography>
          </Box>
          <Box className="flex-center">
            <Typography variant='h4'>
              Footer Here
            </Typography>
          </Box>
        </Box>
      </main>
    </>
  )
}
